# Generated by Django 4.0.2 on 2024-10-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekersprofilemodel',
            name='DisplyName',
        ),
        migrations.RemoveField(
            model_name='recruiters1profilemodel',
            name='DisplyName',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='DisplyName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
