# Generated by Django 4.0.2 on 2024-09-30 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_usertype_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100, null=True)),
                ('NumberOfOpenings', models.PositiveIntegerField(null=True)),
                ('Categry', models.CharField(max_length=100, null=True)),
                ('JobDescription', models.TextField(max_length=1000, null=True)),
                ('RequiredSkills', models.CharField(max_length=100, null=True)),
                ('ApplicationURL', models.URLField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
