# Generated by Django 4.0.2 on 2024-10-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_jobseekersprofilemodel_displyname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruiters1ProfileModel',
            new_name='RecruitersProfileModel',
        ),
    ]
