# Generated by Django 4.0.2 on 2024-10-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_createjobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='GenderType',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Pic',
            field=models.ImageField(null=True, upload_to='user_img'),
        ),
    ]
