# Generated by Django 4.0.2 on 2024-10-22 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_recruiters1profilemodel_recruitersprofilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=255, null=True)),
                ('com_title', models.CharField(max_length=255, null=True)),
                ('com_description', models.TextField(null=True)),
                ('com_logo', models.ImageField(null=True, upload_to='static/Midea/company_logos')),
                ('com_location', models.CharField(max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('num_openings', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('job_description', models.TextField(null=True)),
                ('qualifications', models.TextField(null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('deadline', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
