# Generated by Django 4.0.2 on 2024-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_city_customuser_gendertype_customuser_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createjobmodel',
            old_name='NumberOfOpenings',
            new_name='num_openings',
        ),
        migrations.RenameField(
            model_name='createjobmodel',
            old_name='Categry',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='createjobmodel',
            name='ApplicationURL',
        ),
        migrations.RemoveField(
            model_name='createjobmodel',
            name='JobDescription',
        ),
        migrations.RemoveField(
            model_name='createjobmodel',
            name='JobTitle',
        ),
        migrations.RemoveField(
            model_name='createjobmodel',
            name='RequiredSkills',
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='com_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='com_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='com_logo',
            field=models.ImageField(null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='com_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='com_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='job_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createjobmodel',
            name='qualifications',
            field=models.TextField(null=True),
        ),
    ]
