# Generated by Django 5.0.6 on 2024-10-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_createjobmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekersprofilemodel",
            name="Bio",
        ),
        migrations.RemoveField(
            model_name="jobseekersprofilemodel",
            name="ContractNumber",
        ),
        migrations.RemoveField(
            model_name="jobseekersprofilemodel",
            name="Photo",
        ),
        migrations.RemoveField(
            model_name="jobseekersprofilemodel",
            name="WebLink",
        ),
        migrations.RemoveField(
            model_name="recruitersprofilemodel",
            name="Bio",
        ),
        migrations.RemoveField(
            model_name="recruitersprofilemodel",
            name="ContractNumber",
        ),
        migrations.RemoveField(
            model_name="recruitersprofilemodel",
            name="Photo",
        ),
        migrations.RemoveField(
            model_name="recruitersprofilemodel",
            name="WebLink",
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="Bio",
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="ContractNumber",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="Photo",
            field=models.ImageField(null=True, upload_to="static/Midea/UserPhoto"),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="WebLink",
            field=models.URLField(null=True),
        ),
    ]
