# Generated by Django 5.0.7 on 2024-10-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_createjobmodel_qualifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createjobmodel',
            old_name='category',
            new_name='Category',
        ),
    ]
