# Generated by Django 5.1.2 on 2024-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_category_createjobmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjobmodel',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
