# Generated by Django 5.1.2 on 2024-10-30 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_createjobmodel_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekersprofilemodel',
            name='Skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='createjobmodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Seekers_Profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruitersprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Recruiters_Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
