# Generated by Django 5.1.2 on 2024-10-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customusermodel_contractnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applymodel',
            old_name='user_bio',
            new_name='Upload_Resume',
        ),
        migrations.RemoveField(
            model_name='applymodel',
            name='user_image',
        ),
        migrations.AddField(
            model_name='applymodel',
            name='Cover_Letter',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
