# Generated by Django 5.0.7 on 2024-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_user_bio_applymodel_upload_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
