# Generated by Django 5.0.7 on 2024-11-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customusermodel_contractnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjobmodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware')], max_length=200, null=True),
        ),
    ]
